### ISSUE TITLE
Multiple printing from parallel processes

### ISSUE THREAD

**Issue by sreevarsha** [classner/pymp#14]
Hello,

I'm using this function to parallelise parameter fitting for several objects. Here is my code snippet :

with pymp.Parallel(4) as p:
    fit_plasticc_bazin(path_photo_file=photo_file, 
		           path_header_file=header_file,
		           output_file=output_file, sample=sample)

The function I'm calling reads two files, does the fitting and outputs the results. My problem is that, when I use several (4 here) threads, each object is fit 4 times and I get 4 resultant lines for the same object in my output file. I was wondering, is there a way to constrain the processes so only one result for each object is written into the file during function call or would I have to incorporate it into the function ? Any suggestions/solutions would be much appreciated. Thanks so much.

Cheers !

**Comment by classner** [comment]
Hi @sreevarsha ,

Sure, consider the example in the readme:

```python
# ...
with pymp.Parallel(4) as p:
    for index in p.range(0, 100):  # <- this is the important line, especially the p.range!
        ex_array[index] = 1
```
Use a loop in your code with an iterator similar to this and every process will only receive a part of the range.

**Comment by sreevarsha** [comment]
Hi, Thanks for your reply. That solves the multi printing, but now it runs only one thread. Is there a way to run multiple threads and not have multi printing ? Cheers.

**Comment by classner** [comment]
This should run four threads, as in the example. You can be sure by also printing the thread ID (it is available as `p.thread_num`, the number of threads in total is available as `p.num_threads`. There is also this example in the readme:

```python
with pymp.Parallel(4) as p:
    p.print(p.num_threads, p.thread_num)
```

Does this help? :)

**Comment by sreevarsha** [comment]
It does, thanks so much. It just doesn't show up as multiple threads when htop is run. But when I try this command or ps -ef | grep, the other threads show up. Thanks so much !
