### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Gedeon-m-gedus** [classner/pymp#24]
Hi

I was wondering if you could put it on conda-forge as well.

Thanks

**Comment by classner** [comment]
Hi @Gedeon-m-gedus ,

Thanks for the suggestion, I created a PR above to do this.

**Comment by classner** [comment]
Hi @Gedeon-m-gedus,

It has been successfully merged into conda-forge yesterday.

**Comment by Gedeon-m-gedus** [comment]
Well done
