### ISSUE TITLE
Message when child processes complete?

### ISSUE THREAD

**Issue by laytonjbgmail** [classner/pymp#25]
I apologize for such a newbie question (as were my others).

I have a loop where I start a few child processes. These processes may be relatively long running (several minutes to several hours). I want to know when they complete before starting more child processes. When they complete is there a message indicating this? 

Thanks!

Jeff

**Comment by classner** [comment]
Hi @laytonjbgmail ,

How do you start those processes?

Without that information, some high level ideas: one of the upsides of using pymp is that it abstracts away the need to manage subprocesses. For example, you just use `with pymp.Parallel(max_number_of_processes_you_want):` and pymp makes sure to keep them alive across the execution of anything within that loop and assigns the workloads correctly.

**Comment by laytonjbgmail** [comment]
Thanks for the response!

This example assumes the number of child processes is fixed at 3:

```
    import pymp

    results = pymp.shared.array(3)
    with pymp.Parallel(3) as p:
        for sec_idx in p.xrange(3):
            if (sec_idx == 0):
                p.print('Section 1')
                data1 = [1, 2, 3, 4]
                results[0] = func1(data1)
            elif (sec_idx == 1):
                p.print('Section 2')
                data2 = [5, 6, 7, 8]
                results[1] = func2(data2)
            elif (sec_idx == 2):
                p.print('Section 3')
                data3 = [9, 10, 11, 12, 12, 13, 14, 15]
                results[2] = func3(data3)
            # end if
        # end for
    # end with
```


This example just starts three processes. What I want to do is start 3 processes, wait for them to finish, then start another 3 with different data, and continue that cycle for N iterations. Note: Ultimately, I want to replace "3" with a number that is determined by the input data.

If I understand your comment, in the code above, the loop with sec_idx as the loop counter, won't finish until all 3 processes complete. Is this correct?

If my understanding is correct, then all I would need to do is insert the sample core inside an outer loop that would repeat as many time as I want. Would I need to wrap the outer loop around "results = pymp.shared.array(3)"? The code would look something like the following,

```
    import pymp

    for i_outer in range(4):
        results = pymp.shared.array(3)
        with pymp.Parallel(3) as p:
            for sec_idx in p.xrange(3):
                if (sec_idx == 0):
                    p.print('Section 1')
                    data1 = [1, 2, 3, 4]
                    results[0] = func1(data1)
                elif (sec_idx == 1):
                    p.print('Section 2')
                    data2 = [5, 6, 7, 8]
                    results[1] = func2(data2)
                elif (sec_idx == 2):
                    p.print('Section 3')
                    data3 = [9, 10, 11, 12, 12, 13, 14, 15]
                    results[2] = func3(data3)
                # end if
            # end for
        # end with
    # end for

```

Note: I didn't change the data so the child process functions would just repeat the computations, but this is just for illustration.

Thanks!

Jeff

**Comment by classner** [comment]
Hi Jeff,

Exactly, this will work as expected! :) The code in the parallel section will only complete once all sub-processes complete, so it results exactly in the behavior you want.
